const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),{Chess}=require(path.join(root,'vendor/chess.cjs')),C=JSON.parse(fs.readFileSync(path.join(root,'data/course.json'),'utf8'));
assert.equal(C.lessons.length,24);assert.equal(new Set(C.lessons.map(l=>l.title)).size,24);assert.equal(new Set(C.lessons.map(l=>l.teach)).size,24);assert.equal(new Set(C.drills.map(d=>d.id)).size,C.drills.length);assert.equal(new Set(C.drills.map(d=>d.fen)).size,C.drills.length);
for(const l of C.lessons){for(const k of ['goal','teach','example','task','answer','trap','recall'])assert.ok(l[k]&&l[k].length>25,`${l.id}: incomplete ${k}`);assert.ok(l.teach.length>300,`${l.id}: thin explanation`);}
let lines=0,plies=0,tablebases=0,answers=0,modelDiagrams=0;
for(const l of C.lessons)if(l.diagram){modelDiagrams++;const c=new Chess(l.diagram.fen),opp=c.turn()==='w'?'b':'w';assert.ok(!c.isAttacked(c.findPiece({type:'k',color:opp})[0],c.turn()));if(l.diagram.tablebase?.stalemate)assert.ok(c.isStalemate());if(l.diagram.tablebase?.checkmate)assert.ok(c.isCheckmate());}
if(C.repo==='chess11'){const c=new Chess(C.lessons[5].diagram.fen);assert.ok(!c.moves().includes('Kxd3'));assert.ok(new Chess(C.lessons[19].diagram.fen).isStalemate());}
if(C.repo==='chess12'){const c=new Chess(C.lessons[15].diagram.fen);c.move('Re8#');assert.ok(c.isCheckmate());assert.ok(new Chess(C.lessons[16].diagram.fen).isCheckmate());const fork=new Chess(C.lessons[6].diagram.fen);fork.move('Nf7+');assert.ok(fork.isCheck());for(const reply of fork.moves()){const branch=new Chess(fork.fen());branch.move(reply);assert.ok(branch.moves().includes('Nxd8'));}}
for(const d of C.drills){const c=new Chess(d.fen),opp=c.turn()==='w'?'b':'w';assert.ok(!c.isAttacked(c.findPiece({type:'k',color:opp})[0],c.turn()),`${d.id}: nonmoving king in check`);assert.ok(!c.isGameOver(),`${d.id}: already terminal`);assert.ok(d.prompt&&d.hint&&d.explanation);if(d.kind==='move'){const legal=c.moves({verbose:true}).map(m=>m.from+m.to+(m.promotion||''));for(const a of d.answers){assert.ok(legal.includes(a),`${d.id}: illegal accepted move ${a}`);answers++;}}else{for(const a of d.answers)assert.ok(d.options.some(o=>o.value===a),`${d.id}: answer absent`);assert.equal(new Set(d.options.map(o=>o.value)).size,d.options.length);}
 if(d.line){assert.equal(d.line[0].uci,d.answers[0]);for(const x of d.line){const m=c.move({from:x.uci.slice(0,2),to:x.uci.slice(2,4),promotion:x.uci[4]});assert.equal(m.san,x.san);assert.equal(c.fen(),x.fen);plies++;}assert.ok(d.analysis[0].nodes>=200000);lines++;}
 if(d.tablebase){tablebases++;assert.ok(['win','draw','loss'].includes(d.tablebase.category));if(d.kind==='move'){const needed=d.tablebase.category==='win'?'loss':d.tablebase.category==='draw'?'draw':'win';assert.deepEqual(d.answers.slice().sort(),d.tablebase.moves.filter(m=>m.category===needed).map(m=>m.uci).sort());}else assert.equal(d.answers[0],d.tablebase.category);}
}
const pgns=fs.readFileSync(path.join(root,'downloads/exercises.pgn'),'utf8').split(/\n(?=\[Event )/);assert.equal(pgns.length,C.drills.length);for(let i=0;i<pgns.length;i++){const b=new Chess();b.loadPgn(pgns[i]);assert.equal(b.getHeaders().FEN,C.drills[i].fen);}
const html=fs.readdirSync(root).filter(f=>f.endsWith('.html'));let refs=0;for(const name of html){const text=fs.readFileSync(path.join(root,name),'utf8');assert.ok(text.includes('<title>'));assert.ok(text.includes('lang="en"'));const markup=text.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');for(const m of markup.matchAll(/\b(?:href|src)="([^"]+)"/g)){let p=m[1];if(/^(?:https?:|data:|#)/.test(p))continue;p=decodeURIComponent(p.split(/[?#]/)[0]);if(p==='VALIDATION.json')continue;assert.ok(fs.existsSync(path.join(root,p)),`${name}: missing ${p}`);refs++;}}
const report={repository:C.repo,checkedAt:new Date().toISOString(),lessons:C.lessons.length,exercises:C.drills.length,uniqueExercisePositions:new Set(C.drills.map(d=>d.fen)).size,legalAcceptedMoves:answers,stockfishLines:lines,legalPrincipalVariationPlies:plies,exactTablebasePositions:tablebases,pgnGames:pgns.length,htmlPages:html.length,localReferencesChecked:refs,status:'passed',scope:'Checks content structure, position legality, accepted moves, principal variations, tablebase answer consistency, PGN parsing, and local links. Finite engine analysis is not a mathematical proof of uniqueness.'};fs.writeFileSync(path.join(root,'VALIDATION.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
